<a href="https://colab.research.google.com/github/havaledar/econ3740_f26/blob/main/lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [1]:
import pandas as pd

# Reading Stata Files

## Download LFS data

Download LFS from Odesi Nesstar first from https://odesi.ca/en

## read_stata

Once the file is uploaded and the libraries you are going to use imported, you can read it into a DataFrame.

```python
data = pd.read_stata('file.dta')
```

Make sure the filename matches the uploaded file.

You can also reference the full Google Colab filesystem path if needed:

```
data = pd.read_stata('/content/file.dta')
```

For example, we can import a dta file of survey data downloaded from a website:

To read a dta file into a DataFrame:

```python
data = pd.read_stata('LFS-71M0001-E-2023-August_F1.dta')
```

Pandas will automatically convert the data into a DataFrame.

Here is the documentation for read_stata.
https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fpandas.pydata.org%2Fdocs%2Freference%2Fapi%2Fpandas.read_stata.html

## Labels or Values

When you are reading the dta files, you can indicate if you need the values(convert_categoricals = False) or the lables(convert_categoricals = True) for the categorical variables as below. The read_stata by default read the lables not the values.

```python
data = pd.read_stata('LFS-71M0001-E-2023-August_F1.dta', convert_categoricals=False)
```

In [3]:
data_stata_labels = pd.read_stata("/content/LFS-71M0001-E-2022-April_F1.dta")
data_stata_labels

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1,2022,April,Not in labour force,Prince Edward Island,Other CMA or non-CMA,35 to 39 years,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, youngest ...",Youngest child less than 6 years,66
1,2,2022,April,"Employed, absent from work",Saskatchewan,Other CMA or non-CMA,70 and over,NaN,Female,Divorced,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Person not in an economic family,NaN,37
2,3,2022,April,Not in labour force,New Brunswick,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,160
3,4,2022,April,Not in labour force,Ontario,Other CMA or non-CMA,35 to 39 years,NaN,Male,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, no childr...",NaN,269
4,5,2022,April,"Employed, at work",Ontario,Other CMA or non-CMA,30 to 34 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Dual-earner couple, youngest child 0 to 17",Youngest child less than 6 years,385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111703,111704,2022,April,Not in labour force,British Columbia,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,563
111704,111705,2022,April,"Employed, at work",Ontario,Toronto,60 to 64 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, youngest ...",Youngest child 6 to 12 years,1012
111705,111706,2022,April,"Employed, at work",Quebec,Québec,45 to 49 years,NaN,Female,Living in common-law,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Dual-earner couple, youngest child 18 to 24",Youngest child 18 to 24 years,442
111706,111707,2022,April,Not in labour force,British Columbia,Other CMA or non-CMA,65 to 69 years,NaN,Male,Divorced,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Person not in an economic family,NaN,158
111707,111708,2022,April,"Employed, at work",Saskatchewan,Other CMA or non-CMA,40 to 44 years,NaN,Male,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,216

In [6]:

data_stata_values = pd.read_stata('/content/LFS-71M0001-E-2022-April_F1.dta', convert_categoricals=True)
data_stata_values

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1,2022,April,Not in labour force,Prince Edward Island,Other CMA or non-CMA,35 to 39 years,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, youngest ...",Youngest child less than 6 years,66
1,2,2022,April,"Employed, absent from work",Saskatchewan,Other CMA or non-CMA,70 and over,NaN,Female,Divorced,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Person not in an economic family,NaN,37
2,3,2022,April,Not in labour force,New Brunswick,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,160
3,4,2022,April,Not in labour force,Ontario,Other CMA or non-CMA,35 to 39 years,NaN,Male,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, no childr...",NaN,269
4,5,2022,April,"Employed, at work",Ontario,Other CMA or non-CMA,30 to 34 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Dual-earner couple, youngest child 0 to 17",Youngest child less than 6 years,385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111703,111704,2022,April,Not in labour force,British Columbia,Other CMA or non-CMA,70 and over,NaN,Female,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Non-earner couple, no children or none under 25",NaN,563
111704,111705,2022,April,"Employed, at work",Ontario,Toronto,60 to 64 years,NaN,Male,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Single-earner couple, male employed, youngest ...",Youngest child 6 to 12 years,1012
111705,111706,2022,April,"Employed, at work",Quebec,Québec,45 to 49 years,NaN,Female,Living in common-law,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,"Dual-earner couple, youngest child 18 to 24",Youngest child 18 to 24 years,442
111706,111707,2022,April,Not in labour force,British Columbia,Other CMA or non-CMA,65 to 69 years,NaN,Male,Divorced,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Person not in an economic family,NaN,158
111707,111708,2022,April,"Employed, at work",Saskatchewan,Other CMA or non-CMA,40 to 44 years,NaN,Male,"Single, never married",...,NaN,NaN,NaN,NaN,NaN,NaN,Non-student,Person not in an economic family,NaN,216

## Description

In [7]:
data_stata = pd.read_stata('/content/LFS-71M0001-E-2022-April_F1.dta', iterator=True)
data_stata.variable_labels()

{'REC_NUM': 'Order of record in file',
 'SURVYEAR': 'Survey year',
 'SURVMNTH': 'Survey month',
 'LFSSTAT': 'Labour force status',
 'PROV': 'Province',
 'CMA': 'Nine largest CMAs',
 'AGE_12': 'Five-year age group of respondent',
 'AGE_6': 'Age in 2 and 3 year groups, 15 to 29',
 'SEX': 'Sex of respondent',
 'MARSTAT': 'Marital status of respondent',
 'EDUC': 'Highest educational attainment',
 'MJH': 'Single or multiple jobholder',
 'EVERWORK': 'Not currently employed, worked in the past',
 'FTPTLAST': 'Full- or part-time status of last job',
 'COWMAIN': 'Class of worker, main job',
 'IMMIG': 'Immigration status',
 'NAICS_21': 'Industry of main job',
 'NOC_10': 'Occupation at main job',
 'NOC_40': 'Occupation at main job',
 'YABSENT': 'Reason of absence, full week',
 'WKSAWAY': 'Number of weeks absent from work',
 'PAYAWAY': 'Paid for time off, full-week absence only',
 'UHRSMAIN': 'Usual hours worked per week at main job',
 'AHRSMAIN': 'Actual hours worked per week at main job',
 'FTPTMAIN': 'Full- or part-time status at main or only job',
 'UTOTHRS': 'Usual hours worked per week at all jobs',
 'ATOTHRS': 'Actual hours worked per week at all jobs',
 'HRSAWAY': 'Hours away from work, part-week absence only',
 'YAWAY': 'Reason for part-week absence',
 'PAIDOT': 'Paid overtime hours in reference week',
 'UNPAIDOT': 'Unpaid overtime hours in reference week',
 'XTRAHRS': 'Number of overtime or extra hours worked',
 'WHYPT': 'Reason for part-time work',
 'TENURE': 'Job tenure with current employer (months)',
 'PREVTEN': 'Job tenure with previous employer (months)',
 'HRLYEARN': 'Usual hourly wages, employees only',
 'UNION': 'Union status, employees only',
 'PERMTEMP': 'Job permanency, employees only',
 'ESTSIZE': 'Establishment size',
 'FIRMSIZE': 'Firm size',
 'DURUNEMP': 'Duration of unemployment (weeks)',
 'FLOWUNEM': 'Flows into unemployment',
 'UNEMFTPT': 'Unemployed, type of job wanted',
 'WHYLEFTO': 'Reason for leaving job during previous year',
 'WHYLEFTN': 'Reason for leaving job during previous year',
 'DURJLESS': 'Duration of joblessness (months)',
 'AVAILABL': 'Availability during the reference week',
 'LKPUBAG': 'Unemployed, used public employment agency',
 'LKEMPLOY': 'Unemployed, checked with employers directly',
 'LKRELS': 'Unemployed, checked with friends or relatives',
 'LKATADS': 'Unemployed, looked at job ads',
 'LKANSADS': 'Unemployed, placed or answered ads',
 'LKOTHERN': 'Unemployed, other methods',
 'PRIORACT': 'Main activity before started looking for work',
 'YNOLOOK': 'Reason for not looking for work during the reference week',
 'TLOLOOK': 'Temporary layoff, looked for work during the last four weeks',
 'SCHOOLN': 'Current student status',
 'EFAMTYPE': 'Type of economic family',
 'AGYOWNK': 'Age of youngest child',
 'FINALWT': 'Standard final weight'}

## Type

In [8]:
data_stata_type = pd.read_stata('/content/LFS-71M0001-E-2022-April_F1.dta', preserve_dtypes=False)
data_stata_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111708 entries, 0 to 111707
Data columns (total 60 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   REC_NUM   111708 non-null  int64
 1   SURVYEAR  111708 non-null  int64
 2   SURVMNTH  111708 non-null  category
 3   LFSSTAT   111708 non-null  category
 4   PROV      111708 non-null  category
 5   CMA       111708 non-null  category
 6   AGE_12    111708 non-null  category
 7   AGE_6     21142 non-null   category
 8   SEX       111708 non-null  category
 9   MARSTAT   111708 non-null  category
 10  EDUC      111708 non-null  category
 11  MJH       65316 non-null   category
 12  EVERWORK  46392 non-null   category
 13  FTPTLAST  7332 non-null    category
 14  COWMAIN   72648 non-null   category
 15  IMMIG     111708 non-null  category
 16  NAICS_21  72648 non-null   category
 17  NOC_10    72648 non-null   category
 18  NOC_40    72648 non-null   category
 19  YABSENT   5627 non-null    category
 20  WKSAWAY   5627 non-null    float64
 21  PAYAWAY   5055 non-null    category
 22  UHRSMAIN  65316 non-null   float64
 23  AHRSMAIN  65316 non-null   float64
 24  FTPTMAIN  65316 non-null   category
 25  UTOTHRS   65316 non-null   float64
 26  ATOTHRS   65316 non-null   float64
 27  HRSAWAY   51281 non-null   float64
 28  YAWAY     17691 non-null   category
 29  PAIDOT    51281 non-null   float64
 30  UNPAIDOT  51281 non-null   float64
 31  XTRAHRS   51281 non-null   float64
 32  WHYPT     12569 non-null   category
 33  TENURE    65316 non-null   float64
 34  PREVTEN   7332 non-null    float64
 35  HRLYEARN  56063 non-null   float64
 36  UNION     56063 non-null   category
 37  PERMTEMP  56063 non-null   category
 38  ESTSIZE   56063 non-null   category
 39  FIRMSIZE  56063 non-null   category
 40  DURUNEMP  3500 non-null    float64
 41  FLOWUNEM  3799 non-null    category
 42  UNEMFTPT  3799 non-null    category
 43  WHYLEFTO  7332 non-null    category
 44  WHYLEFTN  7332 non-null    category
 45  DURJLESS  39095 non-null   float64
 46  AVAILABL  4655 non-null    category
 47  LKPUBAG   352 non-null     category
 48  LKEMPLOY  1522 non-null    category
 49  LKRELS    1044 non-null    category
 50  LKATADS   2545 non-null    category
 51  LKANSADS  1327 non-null    category
 52  LKOTHERN  766 non-null     category
 53  PRIORACT  3371 non-null    category
 54  YNOLOOK   1445 non-null    category
 55  TLOLOOK   129 non-null     category
 56  SCHOOLN   83092 non-null   category
 57  EFAMTYPE  111708 non-null  category
 58  AGYOWNK   28619 non-null   category
 59  FINALWT   111708 non-null  int64
dtypes: category(43), float64(14), int64(3)
memory usage: 19.1 MB

You can check the not null values with both info and describe.

## pyreadstat

In [9]:
!pip install pyreadstat
import pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.6-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.13/dist-packages (from pyreadstat) (2.26.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pyreadstat) (2.1.3)
Downloading pyreadstat-1.3.6-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 40.8 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.6

In [10]:
d, meta = pyreadstat.read_dta('/content/LFS-71M0001-E-2022-April_F1.dta')

In [11]:
d

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1,2022,4,4,11,0,5,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,6,1,66
1,2,2022,4,2,47,0,12,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,37
2,3,2022,4,4,13,0,12,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,160
3,4,2022,4,4,35,0,5,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,1,5,NaN,269
4,5,2022,4,1,35,0,4,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,3,1,385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111703,111704,2022,4,4,59,0,12,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,563
111704,111705,2022,4,1,35,4,10,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,6,2,1012
111705,111706,2022,4,1,24,1,7,NaN,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,1,4,4,442
111706,111707,2022,4,4,59,0,11,NaN,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,158
111707,111708,2022,4,1,47,0,6,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,216

In [12]:
print(meta.column_labels)

['Order of record in file', 'Survey year', 'Survey month', 'Labour force status', 'Province', 'Nine largest CMAs', 'Five-year age group of respondent', 'Age in 2 and 3 year groups, 15 to 29', 'Sex of respondent', 'Marital status of respondent', 'Highest educational attainment', 'Single or multiple jobholder', 'Not currently employed, worked in the past', 'Full- or part-time status of last job', 'Class of worker, main job', 'Immigration status', 'Industry of main job', 'Occupation at main job', 'Occupation at main job', 'Reason of absence, full week', 'Number of weeks absent from work', 'Paid for time off, full-week absence only', 'Usual hours worked per week at main job', 'Actual hours worked per week at main job', 'Full- or part-time status at main or only job', 'Usual hours worked per week at all jobs', 'Actual hours worked per week at all jobs', 'Hours away from work, part-week absence only', 'Reason for part-week absence', 'Paid overtime hours in reference week', 'Unpaid overtime hours in reference week', 'Number of overtime or extra hours worked', 'Reason for part-time work', 'Job tenure with current employer (months)', 'Job tenure with previous employer (months)', 'Usual hourly wages, employees only', 'Union status, employees only', 'Job permanency, employees only', 'Establishment size', 'Firm size', 'Duration of unemployment (weeks)', 'Flows into unemployment', 'Unemployed, type of job wanted', 'Reason for leaving job during previous year', 'Reason for leaving job during previous year', 'Duration of joblessness (months)', 'Availability during the reference week', 'Unemployed, used public employment agency', 'Unemployed, checked with employers directly', 'Unemployed, checked with friends or relatives', 'Unemployed, looked at job ads', 'Unemployed, placed or answered ads', 'Unemployed, other methods', 'Main activity before started looking for work', 'Reason for not looking for work during the reference week', 'Temporary layoff, looked for work during the last four weeks', 'Current student status', 'Type of economic family', 'Age of youngest child', 'Standard final weight']

In [13]:
meta.variable_value_labels['SURVMNTH']

{1: 'January',
 2: 'February',
 3: 'March',
 4: 'April',
 5: 'May',
 6: 'June',
 7: 'July',
 8: 'August',
 9: 'September',
 10: 'October',
 11: 'November',
 12: 'December'}

# Recent datasets

In [19]:
pd.read_spss('/content/EPA_septembre_2026.sav', convert_categoricals=False)

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,GENDER,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1.0,2026.0,9.0,4.0,13.0,0.0,11.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,104.0
1,2.0,2026.0,9.0,1.0,12.0,0.0,10.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,135.0
2,3.0,2026.0,9.0,1.0,35.0,0.0,10.0,NaN,1.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,18.0,NaN,74.0
3,4.0,2026.0,9.0,3.0,48.0,0.0,6.0,NaN,1.0,2.0,...,NaN,NaN,NaN,0.0,NaN,NaN,1.0,9.0,3.0,149.0
4,5.0,2026.0,9.0,1.0,48.0,0.0,4.0,NaN,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,2.0,155.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113112,113113.0,2026.0,9.0,1.0,35.0,3.0,3.0,6.0,1.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,NaN,382.0
113113,113114.0,2026.0,9.0,1.0,46.0,6.0,5.0,NaN,1.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,174.0
113114,113115.0,2026.0,9.0,4.0,12.0,0.0,10.0,NaN,2.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,141.0
113115,113116.0,2026.0,9.0,1.0,35.0,4.0,7.0,NaN,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,2.0,136.0
113116,113117.0,2026.0,9.0,4.0,24.0,0.0,9.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,18.0,NaN,373.0

In [16]:
d1, m1 = pyreadstat.read_dta('/content/LFS-71M0001-E-2022-April_F1.dta')

In [ ]:
d1

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,LKATADS,LKANSADS,LKOTHERN,PRIORACT,YNOLOOK,TLOLOOK,SCHOOLN,EFAMTYPE,AGYOWNK,FINALWT
0,1,2022,2,4,35,4,1,1,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,2,18,NaN,1168
1,2,2022,2,4,10,0,2,4,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,2,1,NaN,76
2,3,2022,2,4,35,0,7,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,6,2,422
3,4,2022,2,4,24,2,12,NaN,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,290
4,5,2022,2,4,47,0,10,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,8,NaN,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103653,103654,2022,2,1,48,0,9,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,2,NaN,93
103654,103655,2022,2,1,35,5,5,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,3,1,303
103655,103656,2022,2,1,24,0,10,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,68
103656,103657,2022,2,1,59,9,6,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,3,2,225
103657,103658,2022,2,1,13,0,6,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1,18,NaN,179